#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHSIB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.Configuration;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="HHSDatabase")]
	public partial class IBHomeroomDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIB_Homeroom(IB_Homeroom instance);
    partial void UpdateIB_Homeroom(IB_Homeroom instance);
    partial void DeleteIB_Homeroom(IB_Homeroom instance);
    #endregion

    public IBHomeroomDataContext()
        : base(ConfigurationManager.ConnectionStrings["HHSDataBaseConnectionString"].ConnectionString, mappingSource)
    { }
        
		public IBHomeroomDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBHomeroomDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBHomeroomDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBHomeroomDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IB_Homeroom> IB_Homerooms
		{
			get
			{
				return this.GetTable<IB_Homeroom>();
			}
		}
	}
	
	[Table(Name="dbo.IB_Homeroom")]
	public partial class IB_Homeroom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HomeroomId;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHomeroomIdChanging(int value);
    partial void OnHomeroomIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public IB_Homeroom()
		{
			OnCreated();
		}
		
		[Column(Storage="_HomeroomId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HomeroomId
		{
			get
			{
				return this._HomeroomId;
			}
			set
			{
				if ((this._HomeroomId != value))
				{
					this.OnHomeroomIdChanging(value);
					this.SendPropertyChanging();
					this._HomeroomId = value;
					this.SendPropertyChanged("HomeroomId");
					this.OnHomeroomIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
