#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHSIB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HHSDatabase")]
	public partial class IBCalendarDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIB_Calendar(IB_Calendar instance);
    partial void UpdateIB_Calendar(IB_Calendar instance);
    partial void DeleteIB_Calendar(IB_Calendar instance);
    #endregion
		
		public IBCalendarDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBCalendarDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBCalendarDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBCalendarDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IB_Calendar> IB_Calendars
		{
			get
			{
				return this.GetTable<IB_Calendar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IB_Calendar")]
	public partial class IB_Calendar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IBEvent;
		
		private System.DateTime _IBDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIBEventChanging(string value);
    partial void OnIBEventChanged();
    partial void OnIBDateChanging(System.DateTime value);
    partial void OnIBDateChanged();
    #endregion
		
		public IB_Calendar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBEvent", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string IBEvent
		{
			get
			{
				return this._IBEvent;
			}
			set
			{
				if ((this._IBEvent != value))
				{
					this.OnIBEventChanging(value);
					this.SendPropertyChanging();
					this._IBEvent = value;
					this.SendPropertyChanged("IBEvent");
					this.OnIBEventChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime IBDate
		{
			get
			{
				return this._IBDate;
			}
			set
			{
				if ((this._IBDate != value))
				{
					this.OnIBDateChanging(value);
					this.SendPropertyChanging();
					this._IBDate = value;
					this.SendPropertyChanged("IBDate");
					this.OnIBDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
