<?xml version="1.0" encoding="utf-8"?>
<Database Name="HHSDatabase" Class="IBCalendarDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.IB_Calendar" Member="IB_Calendars">
    <Type Name="IB_Calendar">
      <Column Name="IBEvent" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="IBDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>