#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHSIB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HHSDatabase")]
	public partial class IBHhsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHomeroomIB(HomeroomIB instance);
    partial void UpdateHomeroomIB(HomeroomIB instance);
    partial void DeleteHomeroomIB(HomeroomIB instance);
    partial void InsertCalendarIB(CalendarIB instance);
    partial void UpdateCalendarIB(CalendarIB instance);
    partial void DeleteCalendarIB(CalendarIB instance);
    partial void InsertIB_Student(IB_Student instance);
    partial void UpdateIB_Student(IB_Student instance);
    partial void DeleteIB_Student(IB_Student instance);
    partial void InsertIB_Homeroom(IB_Homeroom instance);
    partial void UpdateIB_Homeroom(IB_Homeroom instance);
    partial void DeleteIB_Homeroom(IB_Homeroom instance);
    partial void InsertStudentIB(StudentIB instance);
    partial void UpdateStudentIB(StudentIB instance);
    partial void DeleteStudentIB(StudentIB instance);
    #endregion
		
		public IBHhsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HHSIB"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IBHhsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBHhsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBHhsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IBHhsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HomeroomIB> HomeroomIBs
		{
			get
			{
				return this.GetTable<HomeroomIB>();
			}
		}
		
		public System.Data.Linq.Table<CalendarIB> CalendarIBs
		{
			get
			{
				return this.GetTable<CalendarIB>();
			}
		}
		
		public System.Data.Linq.Table<IB_Student> IB_Students
		{
			get
			{
				return this.GetTable<IB_Student>();
			}
		}
		
		public System.Data.Linq.Table<IB_Homeroom> IB_Homerooms
		{
			get
			{
				return this.GetTable<IB_Homeroom>();
			}
		}
		
		public System.Data.Linq.Table<StudentIB> StudentIBs
		{
			get
			{
				return this.GetTable<StudentIB>();
			}
		}
		
		public System.Data.Linq.Table<IB_Calendar> IB_Calendars
		{
			get
			{
				return this.GetTable<IB_Calendar>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteCalendar")]
		public int DeleteCalendar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HomeroomIB")]
	public partial class HomeroomIB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private EntitySet<StudentIB> _StudentIBs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public HomeroomIB()
		{
			this._StudentIBs = new EntitySet<StudentIB>(new Action<StudentIB>(this.attach_StudentIBs), new Action<StudentIB>(this.detach_StudentIBs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HomeroomIB_StudentIB", Storage="_StudentIBs", ThisKey="ID", OtherKey="HomeroomId")]
		public EntitySet<StudentIB> StudentIBs
		{
			get
			{
				return this._StudentIBs;
			}
			set
			{
				this._StudentIBs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudentIBs(StudentIB entity)
		{
			this.SendPropertyChanging();
			entity.HomeroomIB = this;
		}
		
		private void detach_StudentIBs(StudentIB entity)
		{
			this.SendPropertyChanging();
			entity.HomeroomIB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalendarIB")]
	public partial class CalendarIB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _IBEVent;
		
		private System.Nullable<System.DateTime> _IBDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnIBEVentChanging(string value);
    partial void OnIBEVentChanged();
    partial void OnIBDateChanging(System.Nullable<System.DateTime> value);
    partial void OnIBDateChanged();
    #endregion
		
		public CalendarIB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBEVent", DbType="NVarChar(50)")]
		public string IBEVent
		{
			get
			{
				return this._IBEVent;
			}
			set
			{
				if ((this._IBEVent != value))
				{
					this.OnIBEVentChanging(value);
					this.SendPropertyChanging();
					this._IBEVent = value;
					this.SendPropertyChanged("IBEVent");
					this.OnIBEVentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> IBDate
		{
			get
			{
				return this._IBDate;
			}
			set
			{
				if ((this._IBDate != value))
				{
					this.OnIBDateChanging(value);
					this.SendPropertyChanging();
					this._IBDate = value;
					this.SendPropertyChanged("IBDate");
					this.OnIBDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IB_Student")]
	public partial class IB_Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudentNo;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _Address;
		
		private string _City;
		
		private string _ZipCode;
		
		private string _Email;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Homeroom;
		
		private string _ClassOF;
		
		private string _Parents;
		
		private string _ParentEmail1;
		
		private string _ParentEmail2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentNoChanging(int value);
    partial void OnStudentNoChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhone1Changing(string value);
    partial void OnPhone1Changed();
    partial void OnPhone2Changing(string value);
    partial void OnPhone2Changed();
    partial void OnHomeroomChanging(string value);
    partial void OnHomeroomChanged();
    partial void OnClassOFChanging(string value);
    partial void OnClassOFChanged();
    partial void OnParentsChanging(string value);
    partial void OnParentsChanged();
    partial void OnParentEmail1Changing(string value);
    partial void OnParentEmail1Changed();
    partial void OnParentEmail2Changing(string value);
    partial void OnParentEmail2Changed();
    #endregion
		
		public IB_Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int StudentNo
		{
			get
			{
				return this._StudentNo;
			}
			set
			{
				if ((this._StudentNo != value))
				{
					this.OnStudentNoChanging(value);
					this.SendPropertyChanging();
					this._StudentNo = value;
					this.SendPropertyChanged("StudentNo");
					this.OnStudentNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(20)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(20)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NChar(15)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NChar(10)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(24)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="NVarChar(24)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this.OnPhone1Changing(value);
					this.SendPropertyChanging();
					this._Phone1 = value;
					this.SendPropertyChanged("Phone1");
					this.OnPhone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="NVarChar(24)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this.OnPhone2Changing(value);
					this.SendPropertyChanging();
					this._Phone2 = value;
					this.SendPropertyChanged("Phone2");
					this.OnPhone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Homeroom", DbType="NVarChar(50)")]
		public string Homeroom
		{
			get
			{
				return this._Homeroom;
			}
			set
			{
				if ((this._Homeroom != value))
				{
					this.OnHomeroomChanging(value);
					this.SendPropertyChanging();
					this._Homeroom = value;
					this.SendPropertyChanged("Homeroom");
					this.OnHomeroomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassOF", DbType="NChar(10)")]
		public string ClassOF
		{
			get
			{
				return this._ClassOF;
			}
			set
			{
				if ((this._ClassOF != value))
				{
					this.OnClassOFChanging(value);
					this.SendPropertyChanging();
					this._ClassOF = value;
					this.SendPropertyChanged("ClassOF");
					this.OnClassOFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parents", DbType="NVarChar(50)")]
		public string Parents
		{
			get
			{
				return this._Parents;
			}
			set
			{
				if ((this._Parents != value))
				{
					this.OnParentsChanging(value);
					this.SendPropertyChanging();
					this._Parents = value;
					this.SendPropertyChanged("Parents");
					this.OnParentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentEmail1", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string ParentEmail1
		{
			get
			{
				return this._ParentEmail1;
			}
			set
			{
				if ((this._ParentEmail1 != value))
				{
					this.OnParentEmail1Changing(value);
					this.SendPropertyChanging();
					this._ParentEmail1 = value;
					this.SendPropertyChanged("ParentEmail1");
					this.OnParentEmail1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentEmail2", DbType="NVarChar(24)")]
		public string ParentEmail2
		{
			get
			{
				return this._ParentEmail2;
			}
			set
			{
				if ((this._ParentEmail2 != value))
				{
					this.OnParentEmail2Changing(value);
					this.SendPropertyChanging();
					this._ParentEmail2 = value;
					this.SendPropertyChanged("ParentEmail2");
					this.OnParentEmail2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IB_Homeroom")]
	public partial class IB_Homeroom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HomeroomId;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHomeroomIdChanging(int value);
    partial void OnHomeroomIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public IB_Homeroom()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeroomId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HomeroomId
		{
			get
			{
				return this._HomeroomId;
			}
			set
			{
				if ((this._HomeroomId != value))
				{
					this.OnHomeroomIdChanging(value);
					this.SendPropertyChanging();
					this._HomeroomId = value;
					this.SendPropertyChanged("HomeroomId");
					this.OnHomeroomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentIB")]
	public partial class StudentIB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudentNo;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Address;
		
		private string _City;
		
		private string _ZipCode;
		
		private string _Email;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private System.Nullable<int> _HomeroomId;
		
		private string _ClassOf;
		
		private string _Parents;
		
		private string _ParentEmail1;
		
		private string _ParentEmail2;
		
		private string _Homeroom;
		
		private EntityRef<HomeroomIB> _HomeroomIB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentNoChanging(int value);
    partial void OnStudentNoChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhone1Changing(string value);
    partial void OnPhone1Changed();
    partial void OnPhone2Changing(string value);
    partial void OnPhone2Changed();
    partial void OnHomeroomIdChanging(System.Nullable<int> value);
    partial void OnHomeroomIdChanged();
    partial void OnClassOfChanging(string value);
    partial void OnClassOfChanged();
    partial void OnParentsChanging(string value);
    partial void OnParentsChanged();
    partial void OnParentEmail1Changing(string value);
    partial void OnParentEmail1Changed();
    partial void OnParentEmail2Changing(string value);
    partial void OnParentEmail2Changed();
    partial void OnHomeroomChanging(string value);
    partial void OnHomeroomChanged();
    #endregion
		
		public StudentIB()
		{
			this._HomeroomIB = default(EntityRef<HomeroomIB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StudentNo
		{
			get
			{
				return this._StudentNo;
			}
			set
			{
				if ((this._StudentNo != value))
				{
					this.OnStudentNoChanging(value);
					this.SendPropertyChanging();
					this._StudentNo = value;
					this.SendPropertyChanged("StudentNo");
					this.OnStudentNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NChar(15)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NChar(10)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(24)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="NVarChar(24)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this.OnPhone1Changing(value);
					this.SendPropertyChanging();
					this._Phone1 = value;
					this.SendPropertyChanged("Phone1");
					this.OnPhone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="NVarChar(24)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this.OnPhone2Changing(value);
					this.SendPropertyChanging();
					this._Phone2 = value;
					this.SendPropertyChanged("Phone2");
					this.OnPhone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeroomId", DbType="Int")]
		public System.Nullable<int> HomeroomId
		{
			get
			{
				return this._HomeroomId;
			}
			set
			{
				if ((this._HomeroomId != value))
				{
					if (this._HomeroomIB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHomeroomIdChanging(value);
					this.SendPropertyChanging();
					this._HomeroomId = value;
					this.SendPropertyChanged("HomeroomId");
					this.OnHomeroomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassOf", DbType="NChar(10)")]
		public string ClassOf
		{
			get
			{
				return this._ClassOf;
			}
			set
			{
				if ((this._ClassOf != value))
				{
					this.OnClassOfChanging(value);
					this.SendPropertyChanging();
					this._ClassOf = value;
					this.SendPropertyChanged("ClassOf");
					this.OnClassOfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parents", DbType="NVarChar(50)")]
		public string Parents
		{
			get
			{
				return this._Parents;
			}
			set
			{
				if ((this._Parents != value))
				{
					this.OnParentsChanging(value);
					this.SendPropertyChanging();
					this._Parents = value;
					this.SendPropertyChanged("Parents");
					this.OnParentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentEmail1", DbType="NVarChar(24)")]
		public string ParentEmail1
		{
			get
			{
				return this._ParentEmail1;
			}
			set
			{
				if ((this._ParentEmail1 != value))
				{
					this.OnParentEmail1Changing(value);
					this.SendPropertyChanging();
					this._ParentEmail1 = value;
					this.SendPropertyChanged("ParentEmail1");
					this.OnParentEmail1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentEmail2", DbType="NVarChar(24)")]
		public string ParentEmail2
		{
			get
			{
				return this._ParentEmail2;
			}
			set
			{
				if ((this._ParentEmail2 != value))
				{
					this.OnParentEmail2Changing(value);
					this.SendPropertyChanging();
					this._ParentEmail2 = value;
					this.SendPropertyChanged("ParentEmail2");
					this.OnParentEmail2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Homeroom", DbType="NVarChar(50)")]
		public string Homeroom
		{
			get
			{
				return this._Homeroom;
			}
			set
			{
				if ((this._Homeroom != value))
				{
					this.OnHomeroomChanging(value);
					this.SendPropertyChanging();
					this._Homeroom = value;
					this.SendPropertyChanged("Homeroom");
					this.OnHomeroomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HomeroomIB_StudentIB", Storage="_HomeroomIB", ThisKey="HomeroomId", OtherKey="ID", IsForeignKey=true)]
		public HomeroomIB HomeroomIB
		{
			get
			{
				return this._HomeroomIB.Entity;
			}
			set
			{
				HomeroomIB previousValue = this._HomeroomIB.Entity;
				if (((previousValue != value) 
							|| (this._HomeroomIB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HomeroomIB.Entity = null;
						previousValue.StudentIBs.Remove(this);
					}
					this._HomeroomIB.Entity = value;
					if ((value != null))
					{
						value.StudentIBs.Add(this);
						this._HomeroomId = value.ID;
					}
					else
					{
						this._HomeroomId = default(Nullable<int>);
					}
					this.SendPropertyChanged("HomeroomIB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IB_Calendars")]
	public partial class IB_Calendar
	{
		
		private string _IBEVent;
		
		private System.Nullable<System.DateTime> _IBDate;
		
		public IB_Calendar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBEVent", DbType="NVarChar(50)")]
		public string IBEVent
		{
			get
			{
				return this._IBEVent;
			}
			set
			{
				if ((this._IBEVent != value))
				{
					this._IBEVent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> IBDate
		{
			get
			{
				return this._IBDate;
			}
			set
			{
				if ((this._IBDate != value))
				{
					this._IBDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
